apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-persona-deployment
  namespace: space1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: api-container
          image: danpancho/k8apiperson:0.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: my-configmap-app